//Type for Login
export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";
export const USER_SET_AUTH_DATA = "USER_SET_AUTH_DATA";

//Type for Signup
export const USER_SIGNUP_REQUESTED = "USER_SIGNUP_REQUESTED";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";

//Type for ForgotPassword
export const USER_FORGOTPASSWORD_REQUESTED = "USER_FORGOTPASSWORD_REQUESTED";
export const USER_FORGOTPASSWORD_SUCCESS = "USER_FORGOTPASSWORD_SUCCESS";
export const USER_FORGOTPASSWORD_FAILED = "USER_FORGOTPASSWORD_FAILED";
export const RESET_FORGOTPASSWORD_STATE = "RESET_FORGOTPASSWORD_STATE";

//Type for VerificationCode
export const USER_VERIFICATION_REQUESTED = "USER_VERIFICATION_REQUESTED";
export const USER_VERIFICATION_SUCCESS = "USER_VERIFICATION_SUCCESS";
export const USER_VERIFICATION_FAILED = "USER_VERIFICATION_FAILED";
export const USER_RESEND_VERIFICATION_REQUESTED = "USER_RESEND_VERIFICATION_REQUESTED";
export const USER_RESEND_VERIFICATION_SUCCESS = "USER_RESEND_VERIFICATION_SUCCESS";
export const USER_RESEND_VERIFICATION_FAILED = "USER_RESEND_VERIFICATION_FAILED";
export const RESET_VERIFICATION_STATE = "RESET_VERIFICATION_STATE";

//Type for Contactus
export const USER_CONTACTUS_REQUESTED = "USER_CONTACTUS_REQUESTED";
export const USER_CONTACTUS_SUCCESS = "USER_CONTACTUS_SUCCESS";
export const USER_CONTACTUS_FAILED = "USER_CONTACTUS_FAILED";
export const RESET_CONTACTUS_STATE = "RESET_CONTACTU_STATE";

//Type for Change Password
export const USER_CHANGEPASSWORD_REQUESTED = "USER_CHANGEPASSWORD_REQUESTED";
export const USER_CHANGEPASSWORD_SUCCESS = "USER_CHANGEPASSWORD_SUCCESS";
export const USER_CHANGEPASSWORD_FAILED = "USER_CHANGEPASSWORD_FAILED";
export const RESET_CHANGEPASSWORD_STATE = "RESET_CHANGEPASSWORD_STATE";

//Type for Reset Password
export const USER_RESETPASSWORD_REQUESTED = "USER_RESETPASSWORD_REQUESTED";
export const USER_RESETPASSWORD_SUCCESS = "USER_RESETPASSWORD_SUCCESS";
export const USER_RESETPASSWORD_FAILED = "USER_RESETPASSWORD_FAILED";
export const RESET_RESETPASSWORD_STATE = "RESET_RESETPASSWORD_STATE";


//Type for Edit Profile
export const USER_EDITPROFILE_REQUESTED = "USER_EDITPROFILE_REQUESTED";
export const USER_EDITPROFILE_SUCCESS = "USER_EDITPROFILE_SUCCESS";
export const USER_EDITPROFILE_FAILED = "USER_EDITPROFILE_FAILED";
export const RESET_EDITPROFILE_STATE = "RESET_EDITPROFILE_STATE";

//Type for StaticPage
export const STATIC_PAGE_REQUESTED = "STATIC_PAGE_REQUESTED";
export const STATIC_PAGE_SUCCESS = "STATIC_PAGE_SUCCESS";
export const STATIC_PAGE_FAILED = "STATIC_PAGE_FAILED";

//Type for Home
export const USER_HOME_REQUESTED = "USER_HOME_REQUESTED";
export const USER_HOME_SUCCESS = "USER_HOME_SUCCESS";
export const USER_HOME_FAILED = "USER_HOME_FAILED";
export const USER_ADD_TO_LIKE_REQUESTED = "USER_ADD_TO_LIKE_REQUESTED";
export const USER_ADD_TO_LIKE_SUCCESS = "USER_ADD_TO_LIKE_SUCCESS";
export const USER_ADD_TO_LIKE_FAILED = "USER_ADD_TO_LIKE_FAILED";
export const HOME_SEARCH = "HOME_SEARCH";
export const HOME_PULL_TO_REFRESH = "HOME_PULL_TO_REFRESH";

//Type for Product
export const PRODUCT_DETAIL_REQUESTED = "PRODUCT_DETAIL_REQUESTED";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAILED = "PRODUCT_DETAIL_FAILED";
export const PRODUCT_ADD_TO_LIKE_REQUESTED = "PRODUCT_ADD_TO_LIKE_REQUESTED";
export const PRODUCT_ADD_TO_LIKE_SUCCESS = "PRODUCT_ADD_TO_LIKE_SUCCESS";
export const PRODUCT_ADD_TO_LIKE_FAILED = "PRODUCT_ADD_TO_LIKE_FAILED";

//Type for Catalog
export const CATALOG_REQUESTED = "CATALOG_REQUESTED";
export const CATALOG_SUCCESS = "CATALOG_SUCCESS";
export const CATALOG_FAILED = "CATALOG_FAILED";
export const CATALOG_GO_BACK = "CATALOG_GO_BACK";
export const TOGGLE_ROOT_CATEGORY = "TOGGLE_ROOT_CATEGORY";
export const TOGGLE_ROOT_CATALOG = "TOGGLE_ROOT_CATALOG";

//Type for CatalogProduct
export const CATALOG_PRODUCT_REQUESTED = "CATALOG_PRODUCT_REQUESTED";
export const CATALOG_PRODUCT_SUCCESS = "CATALOG_PRODUCT_SUCCESS";
export const CATALOG_PRODUCT_FAILED = "CATALOG_PRODUCT_FAILED";
export const CATALOG_PRODUCT_PULL_TO_REFRESH = "CATALOG_PRODUCT_PULL_TO_REFRESH";

//Type for CatalogProductFilter
export const CATALOG_PRODUCT_FILTER_REQUESTED = "CATALOG_PRODUCT_FILTER_REQUESTED";
export const CATALOG_PRODUCT_FILTER_SUCCESS = "CATALOG_PRODUCT_FILTER_SUCCESS";
export const CATALOG_PRODUCT_FILTER_FAILED = "CATALOG_PRODUCT_FILTER_FAILED";
export const RESET_CATALOG_PRODUCT_FILTER_STATE = "RESET_CATALOG_PRODUCT_FILTER_STATE";

//Type for Comment
export const COMMENT_LIST_REQUESTED = "COMMENT_LIST_REQUESTED";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAILED = "COMMENT_LIST_FAILED";
export const COMMENT_LIST_LOAD_PREVIOUS = "COMMENT_LIST_LOAD_PREVIOUS";

